# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_auto_20160216_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='lat_long',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
