# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-30 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agency_lat_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
