# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agent_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMailbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('imap', models.CharField(max_length=64)),
                ('imap_port', models.IntegerField()),
                ('smtp', models.CharField(max_length=64)),
                ('smtp_port', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='agentmailbox',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.MailProvider'),
        ),
    ]
