# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_agentsettings'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturesupplier',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='facturesupplier_agency', to='agents.Agency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facturesupplier',
            name='vat',
            field=models.BooleanField(default=True),
        ),
    ]
