# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190910_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturesupplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_supplier', to='finance.Supplier'),
        ),
    ]
