# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-09 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190910_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
