# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-17 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_auto_20191116_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factureseasonal',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='factureseasonal',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='factureseasonal',
            name='sale',
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FactureSeasonal',
        ),
    ]
