# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20191117_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
