# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-18 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20191118_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturenotaire',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
