# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20191118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='factureapporteur',
            name='siret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
