# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-11-25 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_factureapporteur_siret'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturenotaire',
            name='Notaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
