# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-28 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_facturenotaire_notaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturenotaire',
            old_name='Notaire',
            new_name='notaire',
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
