# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-11-27 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_unreadchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unreadchat',
            old_name='msg',
            new_name='message',
        ),
    ]
