# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-27 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
