# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-09 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_clientsearch_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsearch',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 2, 9, 10, 36, 43, 628830, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientsearch',
            name='date_updated',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 2, 9, 10, 36, 52, 885673, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
