# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-24 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20170209_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('what', models.CharField(choices=[(b'appartement', b'Appartement'), (b'villa', b'Villa'), (b'commerce', b'Commerce'), (b'terrain', b'Terrain'), (b'garage', b'Garage')], default=b'apartment', max_length=255)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('trash', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.DeleteModel(
            name='ClientStatus',
        ),
        migrations.AlterField(
            model_name='clientactivity',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
