# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, choices=[(10, b'Partner'), (20, b'Husband'), (30, b'Wife'), (40, b'Brother'), (50, b'Sister'), (60, b'Mother'), (70, b'Father'), (80, b'Cousin'), (90, b'Friend'), (100, b'Assistant'), (110, b'Personal Assistant'), (120, b'Property Manager'), (130, b'Cleaner'), (999, b'Other')], max_length=8, null=True),
        ),
    ]
