# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_clientlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlead',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
