# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_clientlead_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlead',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadagent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientlead',
            name='buying',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientlead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientlead',
            name='selling',
            field=models.TextField(blank=True, null=True),
        ),
    ]
