# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20180406_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlead',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
