# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_clientlead_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlead',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
