# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-11 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0024_clientlead_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlead',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
