# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0026_auto_20180412_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlead',
            name='what',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
