# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-06 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20180811_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hot',
            field=models.BooleanField(default=True),
        ),
    ]
