# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=254)),
                ('mimetype', models.CharField(max_length=254)),
                ('size', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('compressed', models.BooleanField(default=False)),
                ('thumb', models.BooleanField(default=False)),
            ],
        ),
    ]
