# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='compromis_seller_buyer',
            new_name='compromis_sent_seller',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='compromis_signed_sent_buyer',
            new_name='compromis_signed_seller',
        ),
        migrations.AddField(
            model_name='sale',
            name='mortgage_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='signing_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_lost',
            field=models.BooleanField(default=False),
        ),
    ]
